{"uuid": "2fd4fd97-0da6-490e-8511-1b2de459e45d", "children": ["9d8ce613-63ad-41f5-9864-deb2e15e52e9"], "befores": [{"name": "connectDevice", "status": "broken", "statusDetails": {"message": "uiautomator2.exceptions.SessionBrokenError: ('cn.vsx.vc', 'package not found\\n')\n", "trace": "  File \"E:\\atx-pytest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\atx-pytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\atx-pytest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 778, in call_fixture_func\n    res = next(it)\n  File \"E:\\atx-pytest\\TestCases\\conftest.py\", line 29, in connectDevice\n    driver = d.session(\"cn.vsx.vc\")\n  File \"E:\\atx-pytest\\venv\\lib\\site-packages\\uiautomator2\\__init__.py\", line 1079, in session\n    raise SessionBrokenError(pkg_name, resp.text)\n"}, "start": 1551265142833, "stop": 1551265144035}], "start": 1551265142833, "stop": 1551265144168}